# Generated by Django 3.1.7 on 2021-07-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('Feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='userRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_type', models.CharField(choices=[('carpenter', 'carpenter'), ('plumber', 'plumber'), ('mechanic', 'mechanic'), ('construction', 'construction'), ('mining', 'mining'), ('cook', 'cook'), ('teacher', 'teacher')], max_length=50)),
                ('user', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Place', models.CharField(max_length=120)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='workerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Mobile', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('Clint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.userrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(default='ordered', max_length=10)),
                ('worker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerrequest')),
            ],
        ),
    ]
