# Generated by Django 3.1.7 on 2021-07-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workerRequest',
            new_name='workermodel',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
